### PR TITLE
AlertView can be showed correctly when the device is on landscape orientation

### PR DESCRIPTION
**Pull request by jsts**
AlertView can be showed correctly when the device is on landscape orientation

### CODE REVIEW

**Comment by lmcd** [comment]
Will look at this in a little while when at a computer and try to get it merged today :)

**Comment by lmcd** [comment]
@htwu Could you please explain what this PR is doing. `LMAlertView` already handles different orientations and autorotation

**Comment by jsts** [comment]
Yes, you are right, if we keep the alert view showed on the screen then transfer the orientation , the alert view will be ok. 
But if you run the sample on a iPad simulator, before you launch the sample, transfer the orientation of the simulator to landscape , then launch the sample, then trigger the alert view , you will find the orientation of the view is still portrait.

**Comment by leetal** [comment]
I can confirm this is happening in my app too. If i launch the application in landscape and not rotate it, the alertview will show up as in portrait.

**Comment by dhoerl** [comment]
I just grabbed htwu's changes, and its working now opening on an iPad in landscape!

**Pull request merged**
