### PR TITLE
Always vertical center the AlertView

### PR DESCRIPTION
**Pull request by enthouan**
There is also a fix for the delegate which was not calling the right selector.

### CODE REVIEW

**Comment by lmcd** [comment]
There are conflicts - perhaps because I already fixed the delegate call.

**Comment by enthouan** [comment]
Hum, how can we fix the merge issue in github ?

**Comment by lmcd** [comment]
Just push a commit to your branch rectifying the conflicting code

**Comment by lmcd** [comment]
Fixed myself and merged ;)

**Pull request merged**
